experiment:
  dataset: amazon_book
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/validation.tsv
    test_path: ../data/{0}/test.tsv
  binarize: True
  top_k: 20
  evaluation:
    cutoffs: [5, 10, 20]
    simple_metrics: [nDCG, Recall]
    paired_ttest: True
    wilcoxon_test: True
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    NeuMF:
      meta:
        validation_rate: 20
        verbose: True
        save_recs: True
        validation_metric: nDCG@10
      epochs: 500
      batch_size: 512
      mf_factors: [8, 16, 32, 64]
      lr: [0.001, 0.0005, 0.005, 0.0001]
      dropout: 0.1
      is_mf_train: True
      is_mlp_train: True
      m: [4, 8]
      seed: 42
      early_stopping:
        patience: 5
        mode: auto
        monitor: Recall@20
        verbose: True